// gen-qr は URL から QR コードを生成し、RGB565 バイト列の Go ソースファイルを
// 標準出力へ書き出す。
//
// 使い方:
//
//	go run cmd/gen-qr/main.go <URL> <変数名> <サイズ>
//
// 例:
//
//	go run cmd/gen-qr/main.go https://example.com qr 200 > qr.go
package main

import (
	"fmt"
	"image/color"
	"os"
	"strconv"

	qrcode "github.com/skip2/go-qrcode"
)

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintln(os.Stderr, "usage: go run cmd/gen-qr/main.go <url> <varname> <size>")
		os.Exit(1)
	}

	url := os.Args[1]
	varName := os.Args[2]
	size, err := strconv.Atoi(os.Args[3])
	if err != nil || size <= 0 {
		fmt.Fprintln(os.Stderr, "invalid size:", os.Args[3])
		os.Exit(1)
	}

	qr, err := qrcode.New(url, qrcode.Medium)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	qr.DisableBorder = false

	img := qr.Image(size)
	bounds := img.Bounds()
	w := bounds.Dx()
	h := bounds.Dy()

	pixels := make([]byte, w*h*2)
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			c := color.RGBAModel.Convert(img.At(bounds.Min.X+x, bounds.Min.Y+y)).(color.RGBA)
			r5 := uint16(c.R >> 3)
			g6 := uint16(c.G >> 2)
			b5 := uint16(c.B >> 3)
			v := (r5 << 11) | (g6 << 5) | b5
			i := (y*w + x) * 2
			pixels[i] = byte(v >> 8)
			pixels[i+1] = byte(v & 0xFF)
		}
	}

	fmt.Printf("// Code generated by gen-qr from %s. DO NOT EDIT.\n\n", url)
	fmt.Printf("package main\n\n")
	fmt.Printf("const %sW, %sH = %d, %d\n\n", varName, varName, w, h)
	fmt.Printf("var %s = [%sW * %sH * 2]byte{\n", varName, varName, varName)
	for i := 0; i < len(pixels); i += 16 {
		fmt.Printf("\t")
		end := i + 16
		if end > len(pixels) {
			end = len(pixels)
		}
		for _, b := range pixels[i:end] {
			fmt.Printf("0x%02X, ", b)
		}
		fmt.Printf("\n")
	}
	fmt.Printf("}\n")
}
