// gen-avatar は画像ファイルを指定サイズの RGB565 バイト列に変換し、
// Wio Terminal で表示可能な Go ソースファイルを標準出力へ書き出す。
//
// 使い方:
//
//	go run cmd/gen-avatar/main.go <画像ファイル> <変数名> <幅> <高さ>
//
// 例:
//
//	go run cmd/gen-avatar/main.go namecard.jpg avatar 80 80 > avatar.go
//	go run cmd/gen-avatar/main.go Logo_Horizontal_Color.png logo 320 140 > logo.go
package main

import (
	"fmt"
	"image"
	"image/color"
	stdDraw "image/draw"
	_ "image/jpeg"
	_ "image/png"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	if len(os.Args) < 5 {
		fmt.Fprintln(os.Stderr, "usage: go run cmd/gen-avatar/main.go <image> <varname> <width> <height>")
		os.Exit(1)
	}

	imgPath := os.Args[1]
	varName := os.Args[2]
	w, err := strconv.Atoi(os.Args[3])
	if err != nil || w <= 0 {
		fmt.Fprintln(os.Stderr, "invalid width:", os.Args[3])
		os.Exit(1)
	}
	h, err := strconv.Atoi(os.Args[4])
	if err != nil || h <= 0 {
		fmt.Fprintln(os.Stderr, "invalid height:", os.Args[4])
		os.Exit(1)
	}

	f, err := os.Open(imgPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	src, _, err := image.Decode(f)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// RGBA に統一してからリサイズ
	rgba := image.NewRGBA(src.Bounds())
	stdDraw.Draw(rgba, rgba.Bounds(), src, src.Bounds().Min, stdDraw.Src)
	resized := nearestNeighbor(rgba, w, h)

	// RGB565（big-endian）に変換
	pixels := make([]byte, w*h*2)
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			c := color.RGBAModel.Convert(resized.At(x, y)).(color.RGBA)
			r5 := uint16(c.R >> 3)
			g6 := uint16(c.G >> 2)
			b5 := uint16(c.B >> 3)
			v := (r5 << 11) | (g6 << 5) | b5
			i := (y*w + x) * 2
			pixels[i] = byte(v >> 8)
			pixels[i+1] = byte(v & 0xFF)
		}
	}

	// Go ソース出力
	fmt.Printf("// Code generated by gen-avatar from %s. DO NOT EDIT.\n\n", filepath.Base(imgPath))
	fmt.Printf("package main\n\n")
	fmt.Printf("const %sW, %sH = %d, %d\n\n", varName, varName, w, h)
	fmt.Printf("var %s = [%sW * %sH * 2]byte{\n", varName, varName, varName)
	for i := 0; i < len(pixels); i += 16 {
		fmt.Printf("\t")
		end := i + 16
		if end > len(pixels) {
			end = len(pixels)
		}
		for _, b := range pixels[i:end] {
			fmt.Printf("0x%02X, ", b)
		}
		fmt.Printf("\n")
	}
	fmt.Printf("}\n")
}

// nearestNeighbor は最近傍補間でリサイズする。
func nearestNeighbor(src *image.RGBA, w, h int) *image.RGBA {
	dst := image.NewRGBA(image.Rect(0, 0, w, h))
	sb := src.Bounds()
	sw, sh := sb.Dx(), sb.Dy()
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			sx := sb.Min.X + x*sw/w
			sy := sb.Min.Y + y*sh/h
			dst.Set(x, y, src.At(sx, sy))
		}
	}
	return dst
}
